### ISSUE TITLE
Yarn build error

### ISSUE THREAD

**Issue by binloan** [xodio/xod#1996]
### Environment

* Scope: desktop IDE, browser IDE, CLI
* Version: dev
* OS: Windows 10
* Machine: i7, 32 GB RAM
* Python 3.8.3

### Steps to reproduce

git clone project
execute yarn

### Expected behavior

proper install

### Actual behavior

install failure

### Console output 

```bash
yarn install v1.22.4
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@1.1.2: The platform "win32" is incompatible with this module.
info "fsevents@1.1.2" is an optional dependency and failed compatibility check. Excluding it from installation.
info fsevents@1.2.8: The platform "win32" is incompatible with this module.
info "fsevents@1.2.8" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
warning " > eslint-import-resolver-webpack@0.6.0" has incorrect peer dependency "webpack@^1.11.0 || ^2.1.0-beta || ^2.1.0".
warning "workspace-aggregator-74e5f760-e859-4757-bf08-b2149f5719c8 > xod-client-browser > why-did-you-update@0.1.0" has incorrect peer dependency "react@^15.0 || 0.14.x".
warning "workspace-aggregator-74e5f760-e859-4757-bf08-b2149f5719c8 > xod-client-electron > chai-as-promised@6.0.0" has incorrect peer dependency "chai@>= 2.1.2 < 4".
warning "workspace-aggregator-74e5f760-e859-4757-bf08-b2149f5719c8 > xod-client > react-codemirror@1.0.0" has incorrect peer dependency "react@>=15.5 <16".
warning "workspace-aggregator-74e5f760-e859-4757-bf08-b2149f5719c8 > xod-client > react-codemirror@1.0.0" has incorrect peer dependency "react-dom@>=15.5 <16".
warning "workspace-aggregator-74e5f760-e859-4757-bf08-b2149f5719c8 > belt-holes > @glennsl/bs-jest > jest > jest-cli > @jest/core > jest-resolve-dependencies@24.5.0" has unmet peer dependency "jest-resolve@^24.1.0".
warning "workspace-aggregator-74e5f760-e859-4757-bf08-b2149f5719c8 > belt-holes > @glennsl/bs-jest > jest > jest-cli > jest-config > jest-resolve@24.5.0" has unmet peer dependency "jest-haste-map@^24.0.0".
[4/4] Building fresh packages...
[6/9] ⢀ @serialport/bindings                                                                                            [8/9] ⢀ electron                                                                                                        [3/9] ⢀ puppeteer                                                                                                       [-/9] ⢀ waiting...
error C:\Users\...\xod\node_modules\@serialport\bindings: Command failed.
Exit code: 1
Command: prebuild-install --tag-prefix @serialport/bindings@ || node-gyp rebuild
Arguments:
Directory: C:\Users\...\xod\node_modules\@serialport\bindings
Output:
prebuild-install WARN install No prebuilt binaries found (target=10.21.0 runtime=node arch=x64 platform=win32)
gyp info it worked if it ends with ok
gyp info using node-gyp@3.8.0
gyp info using node@10.21.0 | win32 | x64
gyp ERR! configure error
gyp ERR! stack Error: Command failed: C:\Python38\python.EXE -c import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack   File "<string>", line 1
gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack                       ^
gyp ERR! stack SyntaxError: invalid syntax
gyp ERR! stack
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:294:12)
gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
gyp ERR! stack     at maybeClose (internal/child_process.js:982:16)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
gyp ERR! System Windows_NT 10.0.18363
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\...\\xod\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\...\xod\node_modules\@serialport\bindings
```

### How to fix

----

Getting this error when trying to build from source. Am I missing something?

**Comment by binloan** [comment]
Was caused by a dependency issue with Python 3. Apparently we need Node10, Yarn and Python 2.7. Would be great to write the versions needed directly within the README.
